# Generated by Django 4.0.4 on 2022-06-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
    ]
