# Generated by Django 4.0.4 on 2022-06-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
